##########################################################################
# Example Inventory
##########################################################################
#
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
#
##########################################################################

all:
  children:
    kubernetes_cluster: # The group "kubernetes_cluster" contains 2 subgroups called "controllers" and "nodes"
      vars: # The variables apply to the "kubernetes_cluster" group
        ansible_python_interpreter: "/usr/bin/python3"          
      children: # We define the 2 subgroups inside the group "kubernetes_cluster"
        controllers:
          hosts:
            k8smaster1: 
              ansible_host: 172.30.240.11
        nodes:
          hosts:
            k8sworker1: 
              ansible_host: 172.30.240.51
            k8sworker2: 
              ansible_host: 172.30.240.52
              #ansible_user: 
              #ansible_ssh_private_key_file:
          # vars: 
            # ansible_python_interpreter: "/usr/bin/python3"
 
        
   
           

                          
