# -*- mode: ruby -*-
# vi: set ft=ruby :


K8SMASTERS_BOX_IMAGE = "ubuntu2004"
K8SWORKERS_BOX_IMAGE = "ubuntu2004"
K8SMASTERS_COUNT = 1
K8SWORKERS_COUNT = 2

Vagrant.configure("2") do |config|
  
  if Vagrant.has_plugin?("vagrant-proxyconf")
		config.proxy.http     = "http://10.40.56.3:8080"
		config.proxy.https    = "http://10.40.56.3:8080"
		config.proxy.no_proxy = "localhost,127.0.0.1,10.96.0.0/12,192.168.59.0/24,192.168.39.0/24,192.168.49.0/24,192.168.0.0/16,172.30.240.0/20"
  end
	
  (1..K8SMASTERS_COUNT).each do |i|
    config.vm.define "k8smaster#{i}" do |subconfig|
      subconfig.vm.box = K8SMASTERS_BOX_IMAGE
      subconfig.vm.hostname = "k8smaster#{i}"
      subconfig.vm.network "private_network", ip: "172.30.240.#{i + 10}"
      subconfig.vm.network "forwarded_port", guest: 22, host: "222#{i + 10}", id: "ssh"
      subconfig.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 2048]
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.customize ["modifyvm", :id, "--name", "k8smaster#{i}"]
      end
    end
  end
  
  (1..K8SWORKERS_COUNT).each do |i|
    config.vm.define "k8sworker#{i}" do |subconfig|
      subconfig.vm.box = K8SWORKERS_BOX_IMAGE
      subconfig.vm.hostname = "k8sworker#{i}"
      subconfig.vm.network "private_network", ip: "172.30.240.#{i + 50}"
      subconfig.vm.network "forwarded_port", guest: 22, host: "222#{i + 50}", id: "ssh"
      subconfig.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", 1024]
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--name", "k8sworker#{i}"]
      end
    end
  end
  
  # Enable the "PasswordAuthentication" option to be able to log in through SSH with username and password
  config.vm.provision "shell", inline: <<-SHELL
	cp /vagrant/sshd_config /etc/ssh/sshd_config
	systemctl restart ssh
  SHELL
  
end